version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/orders
    depends_on:
      - mongo

  customer-service:
    build: ./customer-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/customers
    depends_on:
      - mongo

  api-gateway:
    build: ./api-gateway     # ✅ dòng này đã được thụt vào đúng
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service
      - customer-service

volumes:
  mongo_data:
